[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pypestutils"
dynamic = ["version"]
authors = [
    {name = "Jeremy White", email = "jtwhite1000@gmail.com"},
    {name = "Mike Taves", email = "mwtoews@gmail.com"},
]
readme = "README.md"
description = "PEST utilities for MODFLOW"
keywords = ["PEST", "MODFLOW", "groundwater", "model"]
license = {text = "Unlicense"}
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Fortran",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Hydrology",
]
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas",
]

[project.optional-dependencies]
optional = [
    "flopy",
    "pyemu",
]
test = [
    "pytest",
]

[project.urls]
Repository = "https://github.com/pypest/pypestutils"

[tool.setuptools]
include-package-data = false

[tool.setuptools.dynamic]
version = {attr = "pypestutils.version.__version__"}

[tool.setuptools.packages.find]
include = ["pypestutils", "pypestutils.*"]

[tool.cibuildwheel]
build = "cp39-*"
build-verbosity = 3
repair-wheel-command = "python scripts/repair_wheel.py -w {dest_dir} {wheel}"
test-requires = "tox"
test-command = "tox --conf {project} --installpkg {wheel}"
test-skip = [
    "*-musllinux*",
    "*aarch64",  # slow!
]
# see also CIBW_ENVIRONMENT_MACOS in release.yml
before-build = [
    "pip install meson ninja wheel",
    "bash {project}/scripts/build_lib.sh",
]

[tool.cibuildwheel.windows]
before-build = "pip install wheel"

[tool.ruff.lint]
select = [
    "D",    # pydocstyle
    "E", "W", # pycodestyle
    "F",    # Pyflakes
    "I",    # isort
    "RET",  # flake8-return
    "UP",   # pyupgrade
]
ignore = [
    "D205",  # 1 blank line required between summary line and description
]

[tool.ruff.lint.per-file-ignores]
"setup.py" = ["D"]
"docs/*.py" = ["D"]
"examples/*" = ["D"]
"scripts/*.py" = ["D"]
"tests/*.py" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
