name: Tests

on: 
  push:

jobs:
  tests:
    name: Tests on ${{ matrix.os }} Python-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.13"]  # run lower and upper versions

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install GCC Fortran (macOS)
        if: runner.os == 'macOS'
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc
          version: 11

      - name: Install build dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pip install meson ninja pandas numpy matplotlib pyemu flopy jupyter notebook nbconvert

      - name: Install build dependencies (macOS)
        if: runner.os == 'Windows'
        run: |
          pip install meson ninja pandas numpy matplotlib pyemu flopy jupyter notebook nbconvert


      - name: Build pestutils (non-Windows)
        if: runner.os != 'Windows'
        run: bash scripts/build_lib.sh

      - name: Install package
        run: pip install .[test,optional]

      - name: Run tests
        run: pytest -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
